version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: recetas
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./app
    depends_on:
      - db
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true

volumes:
  postgres_data: